name: Close Unauthorized PRs

on:
  pull_request:
    types: [opened]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Author
        id: check_author
        run: |
          PR_AUTHOR=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)
          COLLABORATORS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/collaborators" | jq -r '.[].login')
          if [[ ! " $COLLABORATORS " =~ " $PR_AUTHOR " ]]; then
            echo "Unauthorized PR author: $PR_AUTHOR"
            echo "##[set-output name=unauthorized;]true"
          else
            echo "Authorized PR author: $PR_AUTHOR"
            echo "##[set-output name=unauthorized;]false"
          fi
      - name: Close PR if Unauthorized
        if: steps.check_author.outputs.unauthorized == 'true'
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}"
